---
title: "elevateMS Case/Control prediction"
author: "Abhi Pratap"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r global_options, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
Sys.setenv(TZ='GMT')
library(install.load)
install_load(c('plyr', 'tidyverse', 'data.table', 'lubridate', 'ggpubr', 'synapser'))
install_load('ggthemes', 'devtools', "synapser")

synapser::synLogin()
###Load data freeze
load(synGet("syn19273733")$path)

```



```{r}
## Single congition score per user
single_perHC_nQOL_lowExtremity <- nQOL_lowExtremity %>% 
  group_by(healthCode) %>% summarise(TScore = mean(TScore, na.rm=T))
single_perHC_nQOL_uppExtremity <- nQOL_uppExtremity %>% 
  group_by(healthCode) %>% summarise(TScore = mean(TScore, na.rm=T))
single_perHC_nQOL_cognition <- nQOL_cognition %>% 
  group_by(healthCode) %>% summarise(TScore = mean(TScore, na.rm=T))
```


```{r}
#Assay specific probabilities predicted based on a Random forest method
tremor_assay_probab <- fread(synGet("syn20540122")$path, data.table = F) %>% 
  dplyr::mutate(feature = 'tremor') %>%
  inner_join(baselineChar %>% select(healthCode, dataGroups)) %>% 
  filter(dataGroups == 'ms_patient') %>%
  select(-dataGroups, -prob_probability_estimation, -MS) %>%
  rename(value = prob_classification)


mutate(overallPhysicalAbility = factor(overallPhysicalAbility, levels=c('normal', 'milddisability', 'moderatedisability', 'gaitdisability')))

res <- lm(prob_classification ~ overallPhysicalAbility, data=tremor_assay_probab)
summary(res)
```


```{r, fig.align='center', fig.width=8, fig.height=5, dpi=100}
p <- ggboxplot(tremor_assay_probab, 
               x = "overallPhysicalAbility", y = "prob_classification", 
               font.label = list(size=6, face="plain"),
               legend.title="hand", ylab='MS probablity', width=.5, size=.3,
               palette = c('#247BA0', '#F25F5C'))
my_comparisons <- list( c("normal", "milddisability"), c("normal", "moderatedisability"))
p <- p + stat_compare_means(comparisons = my_comparisons) + # Add pairwise comparisons p-value
  stat_compare_means(label.y = 0, label.x = 1.2, label.size = 0.25) 
p <- p + theme_few()
p

```


```{r}


tmp <- merge(tremor_assay_probab, single_perHC_nQOL_lowExtremity)

colnames(tmp)

ggplot(data=tmp, aes(x=TScore, y=value)) + geom_point()
x1 <- tmp_calc_cor(tremor_assay_probab, single_perHC_nQOL_lowExtremity)
x2 <- tmp_calc_cor(tremor_assay_probab, single_perHC_nQOL_uppExtremity)
x3 <- tmp_calc_cor(tremor_assay_probab, single_perHC_nQOL_cognition)

x1
head(tremor_assay_probab)


source("common_analysis_functions.R")
tmp_calc_cor(tremor_assay_probab, )

single_perHC_nQOL_lowExtremity


```

