---
title: "elevateMS Voice-based DSST feature analysis"
author: "Abhi Pratap"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---


```{r global_options, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
Sys.setenv(TZ='GMT')
library(install.load)
install_load(c('plyr', 'tidyverse', 'data.table', 'lubridate', 'ggpubr', 'synapser'))
install_load('ggthemes', 'devtools', 'gridExtra')
# if (!requireNamespace("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# BiocManager::install("ComplexHeatmap", version = "3.8")
install_load("ComplexHeatmap", "circlize", "RColorBrewer")
synapser::synLogin()

###Load data freeze
load(synGet("syn19273733")$path)
source("common_analysis_functions.R")
```

-----



```{r}
dsstF <- dsst %>% inner_join(baselineChar %>% select(healthCode, dataGroups)) %>%
  dplyr::filter(dataGroups == 'ms_patient' & 
         percentCorrect >= 80)  %>%
  tidyr::gather(feature, value, c("numDigits", "numCorrect",
                                  "percentCorrect", "avgTime", "sdTime", "totalTime" )) %>%
  dplyr::mutate(value = as.numeric(value))

dsstF_week_averaged =  dsstF %>% 
  dplyr::select(healthCode, participant_week, feature, value) %>%
  dplyr::group_by(healthCode, participant_week, feature) %>% 
  dplyr::summarise(mean_value = mean(value, na.rm = T),
                   iqr_value = IQR(value, na.rm = T),
                   median_value = median(value, na.rm = T)) %>%
   dplyr::mutate(value = mean_value)
```


```{r}
## Correlations- All Weeks
neurCog_allWeeks_dsstF <- get_neuroQOL_cors(dsstF_week_averaged)

## Correlations- First common week
neurCog_firstCommonWeek_dsstF <- get_neuroQOL_cors(dsstF_week_averaged, use_first_common_week=T)
```


<br>
<br>

##### Correlation between DSST fearues(All Weeks) with Neuro-QoLs

```{r, fig.align='center', fig.width=14, fig.height=8, dpi=200}
p1 <- ggplot(neurCog_allWeeks_dsstF, aes(x=cor, y=-log10(p.val.adj))) + theme_few() + geom_point(size=.7)  + facet_grid( . ~ survey )
p1 <- p1 + scale_color_manual(values=c("#d01c8b", "#4dac26")) + theme(text = element_text(size=15)) + xlab('correlation(spearman)') + geom_hline(yintercept=2, color='grey30', size=.8) + theme(panel.spacing = unit(2, "lines"))
p1
ggsave("FIGURES/dsstF_n_NeuroQOLs_corr_allWeeks_volcanoPlot.jpeg", plot=p1, height=4, width=10, units="in", dpi=300)
```



##### Scatter plot top 2 DSST features(All Weeks) 


```{r}
#View(neurCog_allWeeks_dsstF %>% arrange(desc(abs(cor))))
p1 <- get_scatter_plot(dsstF_week_averaged, nQOL_cognition_week_avg, x='numCorrect', y='TScore')
p2 <- get_scatter_plot(dsstF_week_averaged, nQOL_cognition_week_avg, x='avgTime', y='TScore')
p3 <- grid.arrange(p1,p2, nrow=1)
p3
ggsave("FIGURES/dsstF_top_2_feature_scatterPlot_allWeek.png", p3, height=3, width=9, units="in", dpi=150)
```




<br>

-----


#####  DSST features(first common week) with Neuro-QoLs


```{r, fig.align='center', fig.width=14, fig.height=8, dpi=200}
p1 <- ggplot(neurCog_firstCommonWeek_dsstF, aes(x=cor, y=-log10(p.val.adj))) + theme_few() + geom_point(size=.7)  + facet_grid( . ~ survey )
p1 <-  p1 + theme(text = element_text(size=15)) + xlab('correlation(spearman)') + geom_hline(yintercept=2, color='grey30', size=.8) + theme(panel.spacing = unit(2, "lines"))
p1
ggsave("FIGURES/walkF_n_NeuroQOLs_corr_firstCommonWeeks_volcanoPlot.jpeg", plot=p1, height=4, width=10, units="in", dpi=300)

```


##### Association between DSST featureacross all weeks with baseline PDDS survey


```{r, fig.align='center', fig.width=8, fig.height=5, dpi=200}
##### PDDS
tmp_baselineChar <- baselineChar %>% 
  filter(!is.na(overallPhysicalAbility)) %>%
  filter(dataGroups == 'ms_patient') %>%
  select(healthCode, overallPhysicalAbility)

dsstF_averaged <- dsstF %>% group_by(healthCode, feature) %>% 
  dplyr::summarise(value = mean(value, na.rm = T)) %>%
  inner_join(tmp_baselineChar) %>%
  mutate(overallPhysicalAbility = factor(overallPhysicalAbility, levels=c('normal', 'milddisability', 'moderatedisability', 'gaitdisability')))

tmp_df <- dsstF_averaged  %>%
  group_by(feature) %>%
  nest() %>%
  mutate(res = purrr::map(data, function(x){
    anova(lm(value ~ overallPhysicalAbility, data=x))
  })) %>%
  mutate(glance = res %>% map(broom::tidy))
tmp_get_anova_pval <- function(x){
  x %>% filter(term == 'overallPhysicalAbility') %>% .$p.value
}
tmp_df <- tmp_df %>% mutate(p.val = unlist(glance  %>% map( tmp_get_anova_pval ))) %>%
  select(-glance, -data, -res)


p <- ggboxplot(dsstF_averaged %>% filter(feature == 'numCorrect'), 
               x = "overallPhysicalAbility", y = "value", 
               font.label = list(size=6, face="plain"),
               ylab='number correct', width=.5, size=.3,
               color = "#F25F5C")
my_comparisons <- list( c("normal", "moderatedisability"), c("normal", "gaitdisability"))
p <- p + stat_compare_means(comparisons = my_comparisons) + # Add pairwise comparisons p-value
  stat_compare_means(label.y = 0, label.x = 1.2, label.size = 0.25) 
p <- p + theme_few()
p
ggsave("FIGURES/dsst_feature_numCorrect_physicalDisability_boxplot.png", p, height=4, width=8, units="in", dpi=300)




```



```{r, syn.store, eval=F}
# Knit html document and push to synapse
thisFilePrefix = "DSST_correlations"
thisFileName = paste0(thisFilePrefix, '.Rmd')
html.obj = rmarkdown::render(thisFileName, output_format = 'html_document')


thisFilePrefix = "DSST_correlations"
thisFileName = paste0(thisFilePrefix, '.Rmd')
gtToken = '~/.ssh/apratap_github_token_20190219.txt';
githubr::setGithubToken(as.character(read.table(gtToken)$V1))
thisRepo <- githubr::getRepo(repository = "Sage-Bionetworks/elevateMS_analysis", ref="branch", refName='master')
thisFile_github_permaLink <- githubr::getPermlink(repository = thisRepo, repositoryPath=paste0('analysis/Analytical_Paper_2/',thisFileName))
thisFile_synapse = File(paste0(thisFilePrefix, '.html'), parentId ='syn11315047')
###Store on Synapse
synStore(thisFile_synapse, executed=thisFile_github_permaLink)
unlink(paste0(thisFilePrefix, '.html'))
```


