---
title: "elevateMS Tremor features analysis"
author: "Abhi Pratap"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---



```{r global_options, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
Sys.setenv(TZ='GMT')
library(install.load)
install_load(c('plyr', 'tidyverse', 'data.table', 'lubridate', 'ggpubr', 'synapser'))
install_load('ggthemes', 'devtools', 'gridExtra')
install_load("ComplexHeatmap", "circlize", "RColorBrewer")
synapser::synLogin()

###Load data freeze
load(synGet("syn19273733")$path)
source("common_analysis_functions.R")
#source("analysis/Analytical_Paper_2/common_analysis_functions.R")
```



```{r}


tmp_tremorF <- tremorF %>% filter(dataGroups == 'ms_patient') %>% 
  tidyr::gather(feature, value, c(TREMOR_FEATURES))

tremorF_week_averaged =  tmp_tremorF %>% 
  select(healthCode, participant_week, hand, feature, value) %>%
  group_by(healthCode, participant_week, hand, feature) %>% 
  dplyr::summarise_all(.funs=c(mean), na.rm=T) 
```


<br>
<br>

```{r, neuroQoLCors}
#####TEMP
options(warn = -1)
## Correlations- All Weeks
neurCog_allWeeks_tremorF <- get_neuroQOL_cors(tremorF_week_averaged, 
                                              additional_group_by='hand', 
                                              use_first_common_week=F,
                                              nPermute = 1000)

##Cacl permutation based p-val
tmp_get_perm_pval <- function(permuteCors, estimate){
 2 * ( sum(permuteCors >= abs(estimate)) / length(permuteCors))
}
neurCog_allWeeks_tremorF <- neurCog_allWeeks_tremorF %>% dplyr::mutate(permute.p.val = map2(corPermuted, estimate, tmp_get_perm_pval))
```


<br>
-----

```{r}
tmp_plot_permute_results <- function(permuteResuls, select_neruoQoL_survey){
  intercepts <- permuteResuls %>% 
    dplyr::filter(survey == select_neruoQoL_survey, hand == "right") %>% dplyr::select(feature, estimate, survey)
  tmp <-  permuteResuls %>%  dplyr::filter(survey == select_neruoQoL_survey, hand == "right") %>% 
    dplyr::select(feature, corPermuted) %>% unnest()
  p <- ggplot(data=tmp, aes(x=corPermuted)) + geom_density() + 
    geom_vline(data=intercepts, aes(xintercept=estimate,color="red")) +  facet_wrap(feature ~ .) 
  p <- p + theme_bw() + xlab('distribution of 1000 random permutations') + ggtitle(select_neruoQoL_survey)
  p + theme(legend.position = "none")
}
```


-----

#### Permutation Results - neuroQOL Cognition

```{r, fig.align="center", fig.width=20, fig.height=15}
tmp_plot_permute_results(neurCog_allWeeks_tremorF, 'neuroQOL Cognition')
```


-----

#### Permutation Results - neuroQOL Lower Extremity

```{r, fig.align="center", fig.width=20, fig.height=15}
tmp_plot_permute_results(neurCog_allWeeks_tremorF, 'neuroQOL Lower Extremity')
```


-----

#### Permutation Results - neuroQOL Upper Extremity

```{r, fig.align="center", fig.width=20, fig.height=15}
tmp_plot_permute_results(neurCog_allWeeks_tremorF, 'neuroQOL Upper Extremity')
```





#### Data Summary (round to 4 decimal points)

```{r}
data_to_show <- neurCog_allWeeks_tremorF %>% select(-corPermuted, -statistic, -p.value, -method, -alternative) %>%
  unnest() %>% 
  dplyr::mutate(adj.permute.p.val = p.adjust(permute.p.val, method="fdr")) %>% 
  dplyr::rename(corr.adj.p.val = p.val.adj,
                spearman.cor = estimate ) %>%
  dplyr::mutate(corr.adj.p.val.log10 = -log10(corr.adj.p.val),
                adj.permute.p.val.log10 = -log10(adj.permute.p.val)) %>%
  dplyr::mutate(spearman.cor = round(spearman.cor, digits=4),
                corr.adj.p.val = round(corr.adj.p.val, digits=4),
                adj.permute.p.val = round(adj.permute.p.val, digits=4)) %>%
  select(-permute.p.val) %>%
  filter(!is.na(spearman.cor))
  
install_load("DT")
DT::datatable(data_to_show %>% select(-corr.adj.p.val.log10, -adj.permute.p.val.log10), rownames=F)
```


----


##### Association Tremor features and baseline PDDS survey

```{r}
##############
##### 
##############
tmp_baselineChar <- baselineChar %>% 
  filter(!is.na(overallPhysicalAbility)) %>%
  filter(dataGroups == 'ms_patient') %>%
  select(healthCode, overallPhysicalAbility) %>%
  mutate(overallPhysicalAbility = factor(overallPhysicalAbility, levels=c('normal', 'milddisability', 'moderatedisability', 'gaitdisability')))

tremorF_averaged <- tremorF_week_averaged %>% group_by(healthCode, hand, feature) %>% 
  dplyr::summarise(value = mean(value, na.rm = T)) %>%
  inner_join(tmp_baselineChar) %>%
  mutate(overallPhysicalAbility = factor(overallPhysicalAbility, levels=c('normal', 'milddisability', 'moderatedisability', 'gaitdisability')))

tmp_df <- tremorF_averaged  %>%
  group_by(feature, hand) %>%
  nest() %>%
  mutate(res = purrr::map(data, function(x){
    anova(lm(value ~ overallPhysicalAbility, data=x))
  })) %>%
  mutate(glance = res %>% map(broom::tidy))

tmp_get_anova_pval <- function(x){
  x %>% filter(term == 'overallPhysicalAbility') %>% .$p.value
}

tmp_df<- tmp_df %>% 
  mutate(p.val = unlist(glance  %>% map( tmp_get_anova_pval ))) %>%
  select(-glance, -data, -res) %>%
  mutate(p.val.adj = p.adjust(p.val, method='fdr'))

knitr::kable(tmp_df %>% arrange(p.val.adj) %>% top_n(-5))
```





```{r, syn.store, eval=F}
# Knit html document and push to synapse
thisFileDir = '/Users/apratap/Dropbox/dev/elevateMS_analysis/analysis/Analytical_Paper_2/'
setwd(thisFileDir)
thisFilePrefix = "tremor_features_analysis"
thisFileName = paste0(thisFilePrefix, '.Rmd')
html.obj = rmarkdown::render(thisFileName, output_format = 'html_document')

thisFilePrefix = "tremor_features_analysis"
thisFileName = paste0(thisFilePrefix, '.Rmd')
gtToken = '~/.ssh/apratap_github_token_20190219.txt';
githubr::setGithubToken(as.character(read.table(gtToken)$V1))
thisRepo <- githubr::getRepo(repository = "Sage-Bionetworks/elevateMS_analysis", ref="branch", refName='master')
thisFile_github_permaLink <- githubr::getPermlink(repository = thisRepo, repositoryPath=paste0('analysis/Analytical_Paper_2/',thisFileName))
thisFile_synapse = File(paste0(thisFilePrefix, '.html'), parentId ='syn11315047')
###Store on Synapse
synStore(thisFile_synapse, executed=thisFile_github_permaLink)
unlink(paste0(thisFilePrefix, '.html'))
```




```{r, fig.align='center', fig.width=8, fig.height=5, dpi=100, eval=F}
p <- ggboxplot(tremorF_averaged %>% filter(feature == 'dfa.tm.IMF1.md_uaacf_accelerometer'), 
               x = "overallPhysicalAbility", y = "value", 
               font.label = list(size=6, face="plain"),
               legend.title="hand", ylab='Tremor feature(dfa.tm.IMF1.md_uaacf_accelerometer)', width=.5, size=.3,
               color = "hand", palette = c('#247BA0', '#F25F5C'))
my_comparisons <- list( c("normal", "milddisability"), c("normal", "moderatedisability"))
p <- p + stat_compare_means(comparisons = my_comparisons) + # Add pairwise comparisons p-value
  stat_compare_means(label.y = 0, label.x = 1.2, label.size = 0.25) 
p <- p + theme_few()
p
```


```{r, fig.align='center', fig.width=14, fig.height=8, dpi=200, eval=F}
##### Correlation of Tremor features with Neuro-QoLs(All Weeks)
install_load("grid")
p1 <- ggplot(neurCog_allWeeks_tremorF, aes(x=cor, y=-log10(p.val.adj), color=hand)) + theme_few() + geom_point(size=.7)  + facet_grid( . ~ survey )
p1 <- p1 + scale_color_manual(values=c("#d01c8b", "#4dac26")) + theme(text = element_text(size=15)) + xlab('correlation(spearman)') + geom_hline(yintercept=2, color='grey30', size=.8) + theme(panel.spacing = unit(2, "lines"))
p1
ggsave("FIGURES/tremorCorrelation_allWeeks_volcanoPlot.jpeg", plot=p1, height=4, width=10, units="in", dpi=300)
```



```{r, fig.align='center', fig.width=8, fig.height=5, dpi=200, eval=F}
##### Scatter plot top 2 Tremor features(All Weeks) 
p1 <- get_scatter_plot(tremorF_week_averaged %>% filter(hand == 'right'), nQOL_uppExtremity_week_avg, 
                       x='sd.fr.IMF2.md_uaacf_accelerometer', y='TScore', use_first_common_week = F)
p2 <- get_scatter_plot(tremorF_week_averaged %>% filter(hand == 'right'), nQOL_uppExtremity_week_avg, 
                       x='skewness.tm.IMF2.md_uavacf_gyroscope', y='TScore', use_first_common_week = F)
p3 <- grid.arrange(p2,p1, nrow=1)
ggsave("FIGURES/tremor_n_NeuroQOLs_top_2_features_scatterPlot_allWeeks.png", p3, height=3, width=9, units="in", dpi=150)
```



