---
title: "ElevateMS - Cognition Data QA/QC"
output:
  html_document: default
  html_notebook: default
---
 


```{r global_options, include=FALSE}
rm(list=ls())
##date: '`r format(Sys.time(), ''%d %B, %Y'')`'
knitr::opts_chunk$set(fig.path='Figs/', echo=FALSE, warning=FALSE, message=FALSE)
```


```{r, include=FALSE}
library(synapseClient)
synapseLogin()
library(install.load)
install_load("sjPlot", "ggplot2", "tidyverse", "flashClust", "DT")
source("loadData.R")

#devtools::install_github("apratap/rbundle")
#source("https://bioconductor.org/biocLite.R")
#biocLite("org.Mm.eg.db")
library("rbundle")
```

```{r}
healthCode_to_externalID <- synTableQuery("select * from syn11439398")
healthCode_to_externalID <- healthCode_to_externalID@values %>% dplyr::select(externalId, healthCode)
healthCode_to_externalID <- healthCode_to_externalID[!duplicated(healthCode_to_externalID),]


demog <- get_demographics()

```
```{r, eval=F}

#View(blockSummary %>% dplyr::group_by(healthCode) %>% dplyr::summarise(n = n()))
#sjt.df(blockSummary)
hist(log10(blockSummary$durationMS/1000), breaks = 100)
summary(lm(logDurationSecs ~ screenScale, data=blockSummary ))
summary(lm(logDurationSecs ~ platform, data=blockSummary ))
```



```{r}
vsstResults <- synTableQuery("select * from syn11309241")
vsstResults <- vsstResults@values
vsstResults <- merge(vsstResults, healthCode_to_externalID, all=T)

userActivity <- getUserActivity()
#get start dates for people 
userStartDates <- vsstResults %>% dplyr::group_by(healthCode) %>% 
  dplyr::summarise(participantStartDate = min(lubridate::date(createdOn)))


#sjt.df(vsstResults)
vsstSummary <- vsstResults %>%  dplyr::group_by(healthCode, blockId) %>% 
  dplyr::summarise(numDigits = n(), 
            activtyStartTime_GMT = min(createdOn),
            numCorrect = sum(accuracy == 'y'),
            percentCorrect = 100 * round(numCorrect/numDigits, digits=2),
            avgTime = mean(durationMS/1000, na.rm=T),
            sdTime = sd(durationMS/1000, na.rm=T),
            totalTime = sum(durationMS/1000, na.rm=T))

vsstSummary <- merge(vsstSummary, userStartDates, all=T)
#vsstSummary <- merge(vsstSummary, demog, all=T)
vsstSummary <- vsstSummary %>% 
  #dplyr::filter(numDigits >= 10) %>%
  dplyr::mutate(activtyStartTime_GMT = lubridate::ymd_hms(activtyStartTime_GMT),
                activtyDate = lubridate::date(activtyStartTime_GMT),
                participant_day = as.numeric(activtyDate-participantStartDate ) + 1,
                participant_week = ((participant_day - 1) %/% 7 ) + 1)

tmp_mean <- function(x){
  mean(x, na.rm = T)
}

vsstSummary_week_averaged =  vsstSummary %>% 
  dplyr::select( -activtyStartTime_GMT, -participant_day, -blockId) %>% 
  dplyr::group_by(healthCode, participant_week) %>% 
  dplyr::summarise_all(.funs=c(tmp_mean))

vsstSummary_week_averaged <- merge(demog, vsstSummary_week_averaged, all=T)
```

#### Total DSST tests completed  - `r nrow(vsstSummary)`

---------

#### Digital Symbol substituion test(DSST) features summary
* numDigits  =  number of digits participants uttered 
* numCorrect =  number of correctly called out digits 
* percentCorrect = percent of digits correctly called
* avgTime = Average time (seconds) a user takes to call out a digit
* sdTime = standard deviation of time (seconds) a user takes to call out a digit
* totalTime = total time a user takes to complete a DSST block

```{r, fig.align='center', fig.width=10, fig.height=6}
cols <- c('numDigits', 'numCorrect', 'percentCorrect', 'avgTime' , 'sdTime', 'totalTime')
density_plots <- lapply(cols, function(col){
  ggdensity(vsstSummary, x = col, add = "mean", rug = TRUE )  
})
ggarrange(plotlist = density_plots, ncol=3, nrow=2)
```

-------------

#### Filtering out data where less than 10 digits are called out in a single DSST block


```{r, fig.align='center', fig.width=10, fig.height=6}
vsstSummary <- vsstSummary %>% dplyr::filter(numDigits > 10)
cols <- c('numDigits', 'numCorrect', 'percentCorrect', 'avgTime' , 'sdTime', 'totalTime')
density_plots <- lapply(cols, function(col){
  ggdensity(vsstSummary, x = col, add = "mean", rug = TRUE )  
})
ggarrange(plotlist = density_plots, ncol=3, nrow=2)
```



```{r, eval=F}
vsstUtteranceResults <- synTableQuery("select * from syn11309244")
vsstUtteranceResults <- vsstUtteranceResults$asDataFrame()
#sjt.df(vsstUtteranceResults)
```




---------


#### SST Features correlation with Neuro-QoL's


```{r}
get_vsst_nQOL_cors <- function(vsst, nQOL_survey){
  nQOL_survey['T_Score'] = nQOL_survey['T-Score']
  nQOL_survey['T-Score'] <- NULL
  nQOL_survey <- nQOL_survey %>% dplyr::select(healthCode, T_Score, rawScore, participant_week)
  nQOL_survey <- nQOL_survey %>% dplyr::group_by(healthCode) %>% dplyr::summarise(T_Score = mean(T_Score))
  tmp_df <- merge(vsst, nQOL_survey)
  tmp_df <- tmp_df %>% tidyr::gather(feature, value, c(16:21) ) %>% 
    dplyr::mutate(value = as.numeric(value), T_Score = as.numeric(T_Score))
  
  cor_res <- tmp_df %>% dplyr::group_by(feature) %>% 
                dplyr::summarise(n= length(value),
                                 totalIndividuals = n_distinct(healthCode),
                                 cor = cor(value, T_Score, use="complete.obs", method="spearman"),
                                 p.val = cor.test(value, T_Score, use="complete.obs", method="spearman")[['p.value']])
  cor_res
}


nQOL_uppExtremity <- get_nQOL_uppExtremity() 
nQOL_lowExtremity  <- get_nQOL_lowExtremity()
nQOL_cognition  <- get_nQOL_cognition()

cor_vsst_nQOL_cog <- get_vsst_nQOL_cors(vsstSummary_week_averaged, nQOL_cognition) %>%
  dplyr::mutate(p.val.adj = p.adjust(p.val, method='fdr'), survey = 'nQOL Cognition')
cor_vsst_nQOL_uppExt <- get_vsst_nQOL_cors(vsstSummary_week_averaged, nQOL_uppExtremity) %>%
  dplyr::mutate(p.val.adj = p.adjust(p.val, method='fdr'), survey = 'nQOL Upper Extremity')
cor_vsst_nQOL_lowExt <- get_vsst_nQOL_cors(vsstSummary_week_averaged, nQOL_lowExtremity) %>%
  dplyr::mutate(p.val.adj = p.adjust(p.val, method='fdr'), survey = 'nQOL Lower Extremity')
cor_vsst <- rbind(cor_vsst_nQOL_cog, cor_vsst_nQOL_uppExt, cor_vsst_nQOL_lowExt) %>%
  dplyr::mutate(cor = round(cor, digits=3),
                p.val = round(p.val, digits=3),
                p.val.adj = round(p.val.adj, digits=3))
datatable(cor_vsst, options = list(pageLength = 10), rownames=F)
```



```{r}
library(grid)
p1 <- ggplot(cor_vsst, aes(x=cor, y=-log10(p.val.adj))) + theme_few() + geom_jitter()  
p1 + facet_grid( . ~ survey ) + theme(text = element_text(size=15)) + xlab('correlation(spearman)') + geom_hline(yintercept=2, color='grey30', size=.8) + theme(panel.spacing = unit(2, "lines"))
```

--------


#### SST Feature scatter plots w/ Nuero-QoL Upper Extremity

```{r, fig.align='center', fig.width=10, fig.height=5}
get_scatter_plot <- function(features, survey, selected_feature){
  survey['T_Score'] = survey['T-Score']
  survey['T-Score'] <- NULL
  survey <- survey %>% select(healthCode, T_Score, rawScore, participant_week)
  tmp_df <- merge(features, survey)
  
  ggscatter(tmp_df, x ='T_Score' , y = selected_feature,
            size = .3,
            add = "reg.line",  # Add regressin line
            add.params = list(color = "grey10", fill = "lightgray"),
            conf.int = TRUE, 
            cor.coef = TRUE,
            cor.method = "spearman",
            cor.coef.size = 4.5,
            cor.coeff.args = list(method = "pearson", fontface="italic",
                                label.x.npc = "right", colour = "black",
                                label.y.npc = "top")
   )
}

p1 <- get_scatter_plot(vsstSummary_week_averaged, nQOL_uppExtremity, 'numCorrect')
p2 <- get_scatter_plot(vsstSummary_week_averaged, nQOL_uppExtremity, 'avgTime')
p <- grid.arrange(p1,p2, ncol=2)
```


--------


#### SST Feature Learning Curve - Cohort level


```{r, fig.align='center', fig.width=5, fig.height=5}
selected_individuals <- vsstSummary %>%
  dplyr::group_by(healthCode) %>% 
  dplyr::summarise(n=n()) %>%
  dplyr::filter(n > 15) %>% .$healthCode

tmp_df <- vsstSummary %>% dplyr::filter(healthCode %in% selected_individuals)

ggplot(data=tmp_df, aes(x=participant_day, y=numCorrect)) + geom_point() + geom_smooth() + theme_bw()
ggplot(data=tmp_df, aes(x=participant_day, y=numDigits)) + geom_point() + geom_smooth() + theme_bw()

# 
# hist(table(tmp_df$participant_day))
# selected_individuals
# 
# hist(table(vsstSummary$healthCode))
# table(tmp_df$participant_day)
# 
# interaction.plot(tmp_df$participant_day, tmp_df$healthCode, 
#                  tmp_df$numCorrect, xlab="time", ylab="#correct", legend=F)
```


 
--------

#### SST Feature Learning Curve - Individual level

```{r,  fig.align='center', fig.width=8, fig.height=10}
ggplot(data=tmp_df, aes(x=participant_day, y=numCorrect)) + geom_point() + geom_smooth() + facet_grid(healthCode ~ .) + theme_bw()
```




