---
title: "elevateMS demographics summary"
author: "Abhi Pratap"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r global_options, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
Sys.setenv(TZ='GMT')
library(install.load)
install_load(c('plyr', 'tidyverse', 'data.table', 'lubridate', 'ggpubr', 'synapser'))
install_load('ggthemes', 'devtools', 'gridExtra', "tableone", "table1")
# if (!requireNamespace("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# BiocManager::install("ComplexHeatmap", version = "3.8")
install_load("ComplexHeatmap", "circlize", "RColorBrewer")
synapser::synLogin()


###Load data freeze
load(synGet("syn19273733")$path)
#source("analysis/Analytical_Paper_2/common_analysis_functions.R")
source("common_analysis_functions.R")
```


### Baseline Summary
* Total enrolled: `r n_distinct(baselineChar$healthCode)`
* Participants Dropped: `r sum(baselineChar$dataGroups == 'Ignore')`
* Numbers in three groups: `r paste0(names(table(baselineChar$group)), '-', table(baselineChar$group))`




### Demographic Summary (with missing data)

```{r}
##########
#1. Demog- comparison between case, MS and MS with clinical referral
##########

### Potential errors in self-reported stats
### controls who report data that is indicative of MS patient 
baselineChar_flt <- baselineChar %>% filter(dataGroups %in% c('control', 'ms_patient'))

#Create a variable list which we want in Table 1
listVars <- c("age", "gender", "race", "education", "health_insurance", 
              "employment")
#Define categorical variables
catVars <- c("gender", "race", "education","health_insurance", "employment")


#### Demog table without missing 
demogTable_withOut_missing = tableone::CreateTableOne(data=baselineChar_flt, vars=listVars, factorVars = catVars, 
                                                   strata = c("group"), includeNA = F)
demogTable_withOut_missing_mat <- print(demogTable_withOut_missing, quote = FALSE, noSpaces = TRUE, printToggle = FALSE)

## Save to a CSV file
write.csv(demogTable_withOut_missing_mat, file = "elevateMS_overall_demog_table_withoutMissingData.csv")


#### Demog table with missing 
demogTable_with_missing = tableone::CreateTableOne(data=baselineChar_flt, vars=listVars, factorVars = catVars, 
                                                   strata = c("group"), includeNA = T)

demogTable_with_missing_mat <- print(demogTable_with_missing, quote = FALSE, noSpaces = TRUE, printToggle = FALSE)
#demogTable_with_missing_mat
## Save to a CSV file
write.csv(demogTable_with_missing_mat, file = "elevateMS_overall_demog_table_withMissingData.csv")

table1::table1(~ age + gender + race + education + health_insurance + employment | group, data=baselineChar_flt, overall="Total")
```



-----

### MS Disease Characteristics

```{r}
##########
#2. Within MS - clinical vs in-the wild referral
##########
#Create a variable list which we want in Table 1
listVars <- c("currentDiagnosis", "msFamilyHistory",
              "YearsSinceDiagnosis", "currentDMT", "YearsSinceFirstDMT", "overallPhysicalAbility")
#Define categorical variables
catVars <- c( "currentDiagnosis", "currentDMT", "msFamilyHistory",
             "health_insurance", "employment", "userSharingScope", "overallPhysicalAbility")

tmp_data <- baselineChar_flt %>% filter(dataGroups == 'ms_patient')
demogTable = CreateTableOne(data=tmp_data, vars=listVars, factorVars = catVars, strata = c("group"), includeNA = T)
demogTableMat <- print(demogTable, quote = FALSE, noSpaces = TRUE, printToggle = FALSE)
#demogTableMat
## Save to a CSV file
write.csv(demogTableMat, file = "elevateMS_MSpatients_diseaseChars_table.csv")

table1(~ currentDiagnosis + currentDMT + msFamilyHistory +
         health_insurance + employment  + userSharingScope + overallPhysicalAbility | group, 
       data=tmp_data,overall="Total")

```



```{r, syn.store, eval=F}
# Knit html document and push to synapse
getwd()
thisFilePrefix = "analysis/Analytical_Paper_2/demographics_summary"
thisFileName = paste0(thisFilePrefix, '.Rmd')
html.obj = rmarkdown::render(thisFileName, output_format = 'html_document')

thisFilePrefix = "analysis/Analytical_Paper_2/demographics_summary"
thisFileName = paste0(thisFilePrefix, '.Rmd')
gtToken = '~/.ssh/apratap_github_token_20190219.txt';
githubr::setGithubToken(as.character(read.table(gtToken)$V1))
thisRepo <- githubr::getRepo(repository = "Sage-Bionetworks/elevateMS_analysis", ref="branch", refName='master')
thisFile_github_permaLink <- githubr::getPermlink(repository = thisRepo, repositoryPath=thisFileName)
thisFile_synapse = File(paste0(thisFilePrefix, '.html'), parentId ='syn11315047')
###Store on Synapse
synStore(thisFile_synapse, executed=thisFile_github_permaLink)
unlink(paste0(thisFilePrefix, '.html'))
```




```{r,eval=F}
####################
#Data Missingness
####################
install_load("naniar")
tmp <- baselineChar_flt %>% select(-error, -externalId, -group)
missingNess_overall <- gg_miss_var(tmp, show_pct = T) +  theme(axis.text.y = element_text(size=13)) 
missingNess_control <- gg_miss_var(tmp %>% filter(dataGroups == 'control'),
                                   show_pct = T) +  theme(axis.text.y = element_text(size=13)) 
missingNess_MS <- gg_miss_var(tmp %>% filter(dataGroups == 'ms_patient'), show_pct = T) +  theme(axis.text.y = element_text(size=13)) 
missingNess_MS_referred_cohort <- gg_miss_var(tmp %>% filter(dataGroups == 'ms_patient' & referred_by_clinician == T), show_pct = T) + theme(axis.text.y = element_text(size=13)) 
missingness <- rbind(missingNess_overall$data %>% dplyr::mutate(missingness = 'overall') ,
                     missingNess_MS$data %>% dplyr::mutate(missingness = 'MS'),
                     missingNess_MS_referred_cohort$data %>% dplyr::mutate(missingness = 'MS(referred)'),
                     missingNess_control$data %>% dplyr::mutate(missingness = 'controls'))

missingness <- missingness %>% 
  mutate(missingness = factor(missingness, levels=c('overall', 'MS', 'MS(referred)', 'controls' )),
         variable = factor(variable, levels=rev(missingNess_overall$data$variable)))
p <- ggplot(data=missingness, aes(x=variable, y=pct_miss)) + geom_bar(stat = "identity", position = "dodge", width = 0.7) 
p <- p + geom_vline(xintercept=50, linetype="dashed", color = "red") + ylab('percent')
p <- p + coord_flip() + facet_grid(. ~ missingness) + theme_bw() + theme(text = element_text(size=20))
p
ggsave("analysis/engagement_Paper_1/FINAL_FIGS/supplementary_data_missingness.png", plot=p,
       width = 15, height = 10, dpi = 300, units="in")

```

```{r,eval=F}

#### % Data contributed by MS patients
prop.table(table(userActivity$dataGroups))

### Pariticipant active for how many days?
userActiveDays= userActivity %>% 
  dplyr::filter(dataGroups %in% c('control', 'ms_patient')) %>%
  dplyr::group_by(healthCode, dataGroups) %>% 
  dplyr::summarise(numDays = n_distinct(participant_day)) %>% 
  as.data.frame()


p <- ggplot(data=userActiveDays, aes(x = dataGroups, y = numDays,
                                     fill = dataGroups))
p <- p + geom_boxplot() + theme_few() + scale_fill_manual(values=c(COL_CONTROL, COL_MS_PATIENT)) +  theme(text = element_text(size=12))
p <- p + theme(legend.position = c(.95, .95), legend.justification = c("right", "top"), legend.box.just = "right", legend.title = element_blank())
p <- p + ylab('#Days') + xlab('')
p
ggsave("~/dev/elevateMS_analysis/analysis/engagement_Paper_1/FINAL_FIGS/daysActive.jpeg", plot=p, height=3, width=4, units="in", dpi=150)
ggsave("~/dev/elevateMS_analysis/analysis/engagement_Paper_1/FINAL_FIGS/daysActive.tiff", plot=p, height=3, width=4, units="in", dpi=150)


#users who were active only for first 2 days
users_active_2days_only <- userActiveDays %>% filter(numDays <= 2) %>% .$healthCode
baselineChar %>% filter(healthCode %in% users_active_2days_only) %>% .$dataGroups %>% table()

#users who were active > 1 days
users_active_gt_2day <- userActiveDays %>% filter(numDays > 2) %>% .$healthCode
totalN_selectusers <- baselineChar %>% filter(healthCode %in% users_active_gt_2day) %>% .$dataGroups %>% table()
totalN_selectusers <- data.frame(totalN = as.numeric(totalN_selectusers),dataGroups = names(totalN_selectusers))

#sumamry stats on active days / user
userActiveDays %>% group_by(dataGroups) %>% dplyr::summarise(meanDays = mean(numDays, na.rm=T),
                                                                sdDays = sd(numDays, na.rm=T))
# independent 2-group Mann-Whitney U Test 
wilcox.test(numDays ~ dataGroups, data=userActiveDays)
```


