---
title: "ElevateMS - Top patient reported symptoms and triggers of MS"
author: "Abhi Pratap"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---



```{r global_options, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
Sys.setenv(TZ='GMT')
library(install.load)
install_load(c('plyr', 'tidyverse', 'data.table', 'lubridate', 'ggpubr', 'synapser'))
install_load('ggthemes', 'devtools')
# if (!requireNamespace("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# BiocManager::install("ComplexHeatmap", version = "3.8")
install_load("ComplexHeatmap", "circlize", "RColorBrewer")
synapser::synLogin()

###Load data freeze
load(synGet("syn19273733")$path)
source("common_analysis_functions.R")
```



#### What percentage of people report each Symptom?

```{r, fig.align='center', fig.width=5, fig.height=7, dpi=100}
## n_distinct(symptoms$healthCode)
#### What percentage of people report each symptom?
symptom_summary <- symptoms %>% mutate(symptom = gsub('_', ' ' ,symptom)) %>%
  group_by(symptom) %>% 
  dplyr::summarise(people = n_distinct(healthCode), 
                   percent = round( (people / n_distinct(symptoms$healthCode)) * 100, digits=2))

p <- ggdotchart(symptom_summary, x = "symptom", y = "percent",
           sorting = "descending",                       
           rotate = TRUE,                                
           dot.size = 2,                                 
           y.text.col = TRUE,                           
           ggtheme = theme_pubr() ) + theme_cleveland() 
p
ggsave(file = "FIGURES/symptoms.png",
       plot=p,  height = 10, width = 6, dpi = 200)

```

#### What percentage of people report each Triggers?


```{r fig.align='center', fig.width=5, fig.height=7, dpi=100}
#### What percentage of people report each symptom?
trigger_summary <- triggers %>%
  filter(! (trigger %in% unique(symptoms$symptom))) %>% ##### IMP - Possible bug -- removing the triggers that are reported as symptoms
  mutate(trigger = gsub('_', ' ' , trigger)) %>%
  group_by(trigger) %>% 
  dplyr::summarise(people = n_distinct(healthCode), 
                   percent = round( (people / n_distinct(triggers$healthCode)) * 100, digits=2))

p <- ggdotchart(trigger_summary, x = "trigger", y = "percent",
                sorting = "descending",                       
                rotate = TRUE,                                
                dot.size = 2,                                 
                y.text.col = TRUE,                           
                ggtheme = theme_pubr() ) + theme_cleveland() 
p

ggsave(file = "FIGURES/triggers.png",
       plot=p,  height = 10, width = 6, dpi = 300)
```


#### Symptoms WordCloud

```{r, fig.align='center', fig.width=4, fig.height=4, dpi=100}
install_load("wordcloud")
set.seed(1234)
#png("FINAL_FIGS/symptomsWordCloud.png", height = 5, width = 5, res = 150, units="in" )
wordcloud(words = symptom_summary$symptom, freq = round(symptom_summary$percent), min.freq = 2,
          max.words=50, random.order=FALSE, rot.per=0.30,
          #vfont=c("sans serif","plain"),
          colors=brewer.pal(8, "Dark2"))
#dev.off()

```



#### Triggers WordCloud


```{r, fig.align='center', fig.width=4, fig.height=4, dpi=100}
install_load("wordcloud")
set.seed(1234)
#png("~/FIGURES/triggersWordCloud.png", height = 4, width = 4, res = 150, units="in" )
wordcloud(words = trigger_summary$trigger, freq = round(trigger_summary$percent), min.freq = 2,
          max.words=50, random.order=FALSE, rot.per=0.30,
          #vfont=c("sans serif","plain"),
          colors=brewer.pal(8, "Dark2"))
#dev.off()

```


#### Association between Weather and Symtpoms/Triggers

```{r}
triggers_flt <- triggers %>%
  dplyr::filter(! (trigger %in% unique(symptoms$symptom))) %>%
  dplyr::mutate(trigger_date = as.Date(activity_start_timestamp_local)) %>%
  select(healthCode, trigger_date, trigger ) %>%
  distinct()

symptoms_flt <- symptoms %>%
  dplyr::mutate(symptom_date = as.Date(activity_start_timestamp_local)) %>%
  select(healthCode, symptom_date, severity, symptom ) %>%
  distinct()

weatherF_flt <- weatherF %>%
  dplyr::mutate(weather_date = as.Date(timestamp)) %>%
  dplyr::select(healthCode, weather_date, atmosphericPressure, cloudCoverage, currentTemperature, humidity, maximumTemperature, minimumTemperature)


symptoms_N_weather <- merge(symptoms_flt, weatherF_flt, 
                            by.x=c('healthCode', 'symptom_date'), 
                            by.y=c('healthCode', 'weather_date')) %>%
  dplyr::filter(!severity == 'none') %>%
  dplyr::mutate(severity = factor(severity, levels=c('mild', 'moderate', 'severe')))

triggers_N_weather <- merge(triggers_flt, weatherF_flt, 
                            by.x=c('healthCode', 'trigger_date'), 
                            by.y=c('healthCode', 'weather_date'))


# sort(table(symptoms_N_weather$symptom))/nrow(triggers_N_weather) * 100
# ggplot(data=symptoms_N_weather, aes(x=symptom, y=minimumTemperature)) + geom_boxplot() + coord_flip()


# Top symptoms 
top_N_symptoms <- symptom_summary %>% dplyr::top_n(n=10, wt = percent) %>%
  dplyr::mutate(symptom = gsub(' ','_', symptom))

#### Mixed effect modelling
install_load("lme4", "lmerTest", "broom")
res.1 <- lmer(atmosphericPressure ~ symptom  + severity + (1 | healthCode), 
            data=symptoms_N_weather )
res.2 <- lmer(cloudCoverage ~ symptom  + severity + (1 | healthCode), 
            data=symptoms_N_weather )
res.3 <- lmer(currentTemperature ~ symptom  + severity + (1 | healthCode), 
            data=symptoms_N_weather )
res.4 <- lmer(humidity ~ symptom  + severity + (1 | healthCode), 
            data=symptoms_N_weather )
res.5 <- lmer(maximumTemperature ~ symptom  + severity + (1 | healthCode), 
            data=symptoms_N_weather )
res.6 <- lmer(minimumTemperature ~ symptom  + severity + (1 | healthCode), 
            data=symptoms_N_weather )
sjPlot::tab_model(res.1, res.2, res.3, res.4, res.5, res.6, show.ci = F)


#### severity only 
res.1 <- lmer(atmosphericPressure ~  severity + (1 | healthCode), 
            data=symptoms_N_weather )
res.2 <- lmer(cloudCoverage ~ severity + (1 | healthCode), 
            data=symptoms_N_weather )
res.3 <- lmer(currentTemperature ~ severity + (1 | healthCode), 
            data=symptoms_N_weather )
res.4 <- lmer(humidity ~ severity + (1 | healthCode), 
            data=symptoms_N_weather )
res.5 <- lmer(maximumTemperature ~ severity + (1 | healthCode), 
            data=symptoms_N_weather )
res.6 <- lmer(minimumTemperature ~ severity + (1 | healthCode), 
            data=symptoms_N_weather )

# sjPlot::get_model_data(res)
# sjPlot::tab_model(res)
# sjPlot::plot_model(res, show.p = T)
# p <- sjPlot::plot_model(res, type="slope") + theme_bw() + theme(axis.text.y=element_blank())
# p <- p + xlab('study participants')
```

---

### Visual difference in cloud coverage across different severity types

```{r fig.align='center', fig.width=6, fig.height=4, dpi=100}
### Plot top differentiator - cloudCoverage
p <- ggplot(data=symptoms_N_weather, aes(x=severity, y=cloudCoverage)) + geom_boxplot(width=0.6)
p <- p + theme_light(base_size = 12) + xlab('self reported symptom severity')
p
```





#### personalized association between weather N  
```{r}

```



```{r, syn.store, eval=F}
# Knit html document and push to synapse
thisFilePrefix = "symptoms_N_triggers"
thisFileName = paste0(thisFilePrefix, '.Rmd')
html.obj = rmarkdown::render(thisFileName, output_format = 'html_document')

thisFilePrefix = "symptoms_N_triggers"
thisFileName = paste0(thisFilePrefix, '.Rmd')
gtToken = '~/.ssh/apratap_github_token_20190219.txt'
githubr::setGithubToken(as.character(read.table(gtToken)$V1))
thisRepo <- githubr::getRepo(repository = "Sage-Bionetworks/elevateMS_analysis", ref="branch", refName='master')
thisFile_github_permaLink <- githubr::getPermlink(repository = thisRepo, repositoryPath=paste0('analysis/Analytical_Paper_2/',thisFileName))
thisFile_synapse = File(paste0(thisFilePrefix, '.html'), parentId ='syn11315047')
###Store on Synapse
synStore(thisFile_synapse, executed=thisFile_github_permaLink)
unlink(paste0(thisFilePrefix, '.html'))
```



```{r}
#View(triggers %>% filter(healthCode == 'ae28cea8-9dfa-41aa-9692-d6a5e04893df' & trigger == 'headache'))


# ### Symptoms
# symptoms <- symptoms %>% filter(dataGroups == 'ms_patient' & participant_week <= 12 )
# totalSymptoms <- symptoms %>% group_by(healthCode) %>%
#   dplyr::summarise(uniqSymptomsReported = n_distinct(symptom),
#                    TotalTimesSymptomsReported = n_distinct(activity_start_timestamp_GMT)) 
# symptoms_summary <- symptoms %>% group_by(healthCode, symptom) %>%
#   dplyr::summarise(timesReported = n()) %>%
#   inner_join(totalSymptoms) %>%
#   dplyr::mutate( percent = (timesReported / TotalTimesSymptomsReported)*100,
#                  percent_unique = )
#ggplot(data=symptoms_summary, aes(x=symptom, y=percent)) + geom_violin() + coord_flip()


### Triggers
# triggers <- triggers %>% filter(dataGroups == 'ms_patient' & participant_week <= 12 )
# totalTriggers <- triggers %>% group_by(healthCode) %>%
#   dplyr::summarise(uniqTriggersReported = n_distinct(trigger),
#                    TotalTimesTriggersReported = n_distinct(activity_start_timestamp_GMT)) 
# 
# triggers_summary <- triggers %>% group_by(healthCode, trigger) %>%
#   dplyr::summarise(timesReported = n()) %>%
#   inner_join(totalTriggers) %>%
#   dplyr::mutate( percent = (timesReported / TotalTimesTriggersReported)*100)


####  How often are each trigger reported?  
# tmp <- ddply(.data=triggers, 
#              .variables = c('healthCode', 'dataGroups', 'participant_week', 'participant_day'), 
#              .fun = function(df){ 
#                data.frame(trigger = unlist(strsplit(df$triggers, ',')))
#              })
# 
# top_triggers <- sort( round(prop.table(table(tmp$trigger))*100, digits=2), decreasing = T)[1:10]
# top_triggers <- data.frame(symptom = names(top_triggers), percent=as.numeric(top_triggers))
# knitr::kable(top_triggers)

#### What percentage of people report each trigger?
# tmp <- ddply(.data=triggers, .variables = c('healthCode', 'dataGroups', 'participant_week', 'participant_day'), 
#              .fun = function(df){ 
#                data.frame(trigger = unlist(strsplit(df$triggers, ',')))
#              })
# df <- tmp %>% group_by(trigger, dataGroups) %>% dplyr::summarise(people = n_distinct(healthCode)) %>% spread(dataGroups, people) %>% arrange(desc(ms_patient))
# colnames(df) = c('trigger' , 'reported_by_how_many_people')
# df <- df[1:10,]
# knitr::kable(df)

```
