---
title: "elevateMS tapping features analysis"
author: "Abhi Pratap"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---


<!-- ```{r knit2synapse1, eval=FALSE} -->
<!-- library(install.load) -->
<!-- devtools::install_github("Sage-Bionetworks/knit2synapse") -->
<!-- install_load("synapser", "knit2synapse") -->
<!-- synapser::synLogin() -->
<!-- getwd() -->
<!-- knit2synapse::knitToFolderEntity(file = "tapping_features_analysis.Rmd", -->
<!--                                  parentId = "syn11678367", -->
<!--                                  entityName = "Cluster energy features with postural tremor") -->
<!-- ``` -->



```{r global_options, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}


rm(list=ls())
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
Sys.setenv(TZ='GMT')
library(install.load)
install_load(c('plyr', 'tidyverse', 'data.table', 'lubridate', 'ggpubr', 'synapser'))
install_load('ggthemes', 'devtools')
# if (!requireNamespace("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# BiocManager::install("ComplexHeatmap", version = "3.8")
install_load("ComplexHeatmap", "circlize", "RColorBrewer")

source("../loadData.R")
source("common_analysis_functions.R")
```

-----

```{r}
tmp_tapF <- tapF %>% filter(dataGroups == 'ms_patient') %>%
  gather(feature, value, c(10:51,63)) %>%
  select(-c(1:6)) 

tapF_week_averaged =  tmp_tapF %>% select(healthCode, participant_week, hand, feature, value) %>%
  group_by(healthCode, participant_week, hand, feature) %>% 
  dplyr::summarise_all(.funs=c(mean), na.rm=T) 
```

<br>
<br>

#### Correlations of all tapping features with Neuro-QoLs
```{r, neuroQoLCors, echo=T}

## Correlations- All Weeks
neurCog_allWeeks_tapF <- get_neuroQOL_cors(tapF_week_averaged, additional_group_by='hand', use_first_common_week=F)

## Correlations- First common week
neurCog_firstCommonWeek_tapF <- get_neuroQOL_cors(tapF_week_averaged, additional_group_by='hand', use_first_common_week=T)
```

<br>
<br>

##### Tapping features(All Weeks) with Neuro-QoLs

```{r, fig.align='center', fig.width=14, fig.height=8, dpi=200}
install_load("grid")
p1 <- ggplot(neurCog_allWeeks_tapF, aes(x=cor, y=-log10(p.val.adj), color=hand)) + theme_few() + geom_point(size=.7)  + facet_grid( . ~ survey )
p1 <- p1 + scale_color_manual(values=c("#d01c8b", "#4dac26")) + theme(text = element_text(size=15)) + xlab('correlation(spearman)') + geom_hline(yintercept=2, color='grey30', size=.8) + theme(panel.spacing = unit(2, "lines"))
p1
ggsave("FIGURES/tapCorrelation_allWeeks_volcanoPlot.jpeg", plot=p1, height=4, width=10, units="in", dpi=300)
```

##### Scatter plot top 2 tapping features(All Weeks) 

```{r, fig.align='center', fig.width=8, fig.height=5, dpi=200}
p1 <- get_scatter_plot(tapF_week_averaged %>% filter(hand == 'left'), nQOL_uppExtremity_week_avg, 
                       x='numberTaps', y='TScore', use_first_common_week = F)
p2 <- get_scatter_plot(tapF_week_averaged %>% filter(hand == 'left'), nQOL_uppExtremity_week_avg, 
                       x='meanTapInter', y='TScore', use_first_common_week = F)
p3 <- grid.arrange(p2,p1, nrow=1)
#ggsave("FIGURES/tapping_n_NeuroQOLs_top_2_features_scatterPlot_allWeeks.png", p3, height=3, width=9, units="in", dpi=150)
```



<br>

-----


#####  Tapping features(first common week) with Neuro-QoLs

```{r, fig.align='center', fig.width=14, fig.height=8, dpi=200}

p2 <- ggplot(neurCog_firstCommonWeek_tapF, aes(x=cor, y=-log10(p.val.adj), color=hand)) + theme_few() + geom_point(size=.7)  + facet_grid( . ~ survey )
p2 <- p2 + scale_color_manual(values=c("#d01c8b", "#4dac26")) + theme(text = element_text(size=15)) 
p2 <- p2 + xlab('correlation(spearman)') + geom_hline(yintercept=2, color='grey30', size=.8) + theme(panel.spacing = unit(2, "lines"))
p2
ggsave("FIGURES/tap_N_NeuroQOLs_Correlation_firstCommonWeek_volcanoPlot.jpeg", plot=p2, height=4, width=10, units="in", dpi=300)
```


##### Scatter plot top 2 tapping features(first common week) 

```{r, fig.align='center', fig.width=8, fig.height=5, dpi=200}
p1 <- get_scatter_plot(tapF_week_averaged %>% filter(hand == 'left'), nQOL_uppExtremity_week_avg, 
                       x='numberTaps', y='TScore', use_first_common_week = F)
p2 <- get_scatter_plot(tapF_week_averaged %>% filter(hand == 'left'), nQOL_uppExtremity_week_avg, 
                       x='meanTapInter', y='TScore', use_first_common_week = F)
p3 <- grid.arrange(p2,p1, nrow=1)
ggsave("FIGURES/tapping_n_NeuroQOLs_top_2_features_scatterPlot_allWeeks.png", p3, height=3, width=9, units="in", dpi=150)
```




##### Correlation between Number of Taps(averaged across all weeks) and baseline PDDS survey

```{r}
##############
##### 
##############
tmp_baselineChar <- baselineChar %>% 
  filter(!is.na(overallPhysicalAbility)) %>%
  filter(dataGroups == 'ms_patient') %>%
  select(healthCode, overallPhysicalAbility) %>%
  mutate(overallPhysicalAbility = factor(overallPhysicalAbility, levels=c('normal', 'milddisability', 'moderatedisability', 'gaitdisability')))

tapF_averaged <- tapF_week_averaged %>% group_by(healthCode, hand, feature) %>% 
  dplyr::summarise(value = mean(value, na.rm = T)) %>%
  inner_join(tmp_baselineChar) %>%
  mutate(overallPhysicalAbility = factor(overallPhysicalAbility, levels=c('normal', 'milddisability', 'moderatedisability', 'gaitdisability')))

tmp_df <- tapF_averaged  %>%
  group_by(feature, hand) %>%
  nest() %>%
  mutate(res = purrr::map(data, function(x){
    anova(lm(value ~ overallPhysicalAbility, data=x))
  })) %>%
  mutate(glance = res %>% map(broom::tidy))

tmp_get_anova_pval <- function(x){
  x %>% filter(term == 'overallPhysicalAbility') %>% .$p.value
}

tmp_df<- tmp_df %>% 
  mutate(p.val = unlist(glance  %>% map( tmp_get_anova_pval ))) %>%
  select(-glance, -data, -res)
```

```{r, fig.align='center', fig.width=8, fig.height=5, dpi=100}
p <- ggboxplot(tapF_averaged %>% filter(feature == 'numberTaps'), 
               x = "overallPhysicalAbility", y = "value", 
               font.label = list(size=6, face="plain"),
               legend.title="hand", ylab='number of taps', width=.5, size=.3,
               color = "hand", palette = c('#247BA0', '#F25F5C'))
my_comparisons <- list( c("normal", "milddisability"), c("normal", "moderatedisability"))
p <- p + stat_compare_means(comparisons = my_comparisons) + # Add pairwise comparisons p-value
  stat_compare_means(label.y = 0, label.x = 1.2, label.size = 0.25) 
p <- p + theme_few()
p
ggsave("FIGURES/numberTaps_ALLWeeks_with_physicalDisability_boxplot.png", p, height=4, width=8, units="in", dpi=300)
```



```{r, syn.store, eval=F}
# Knit html document and push to synapse
#knitr::knit()
thisFilePrefix = "tapping_features_analysis"
thisFileName = paste0(thisFilePrefix, '.Rmd')
gtToken = '~/.ssh/apratap_github_token_20190219.txt';
githubr::setGithubToken(as.character(read.table(gtToken)$V1))
thisRepo <- githubr::getRepo(repository = "Sage-Bionetworks/elevateMS_analysis", ref="branch", refName='master')
thisFile_github_permaLink <- githubr::getPermlink(repository = thisRepo, repositoryPath=paste0('analysis/Analytical_Paper_2/',thisFileName))


html.obj = rmarkdown::render(thisFileName, output_format = 'html_document')
thisFile_synapse = File(paste0(thisFilePrefix, '.html'), parentId ='syn11315047')

unlink(paste0(thisFilePrefix, '.html'))

###Store on Synapse
synStore(thisFile_synapse, executed=thisFile_github_permaLink)

```

