---
title: "elevateMS walk features analysis"
author: "Abhi Pratap"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r global_options, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
Sys.setenv(TZ='GMT')
library(install.load)
install_load(c('plyr', 'tidyverse', 'data.table', 'lubridate', 'ggpubr', 'synapser'))
install_load('ggthemes', 'devtools', "synapser")
# if (!requireNamespace("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# BiocManager::install("ComplexHeatmap", version = "3.8")
install_load("ComplexHeatmap", "circlize", "RColorBrewer")

synapser::synLogin()
###Load data freeze
load(synGet("syn19273733")$path)
source("common_analysis_functions.R")
```


-----

```{r}
##WALK FEATURE COLS -
#cat(colnames(walkF),sep="', '")
WALK_FEATURES <- c('meanX', 'sdX', 'modeX', 'skewX', 'kurX', 'q1X', 'medianX', 'q3X', 'iqrX', 'rangeX', 'acfX', 'zcrX', 'dfaX', 'cvX', 'tkeoX', 'F0X', 'P0X', 'F0FX', 'P0FX', 'medianF0FX', 'sdF0FX', 'tlagX', 'meanY', 'sdY', 'modeY', 'skewY', 'kurY', 'q1Y', 'medianY', 'q3Y', 'iqrY', 'rangeY', 'acfY', 'zcrY', 'dfaY', 'cvY', 'tkeoY', 'F0Y', 'P0Y', 'F0FY', 'P0FY', 'medianF0FY', 'sdF0FY', 'tlagY', 'meanZ', 'sdZ', 'modeZ', 'skewZ', 'kurZ', 'q1Z', 'medianZ', 'q3Z', 'iqrZ', 'rangeZ', 'acfZ', 'zcrZ', 'dfaZ', 'cvZ', 'tkeoZ', 'F0Z', 'P0Z', 'F0FZ', 'P0FZ', 'medianF0FZ', 'sdF0FZ', 'tlagZ', 'meanAA', 'sdAA', 'modeAA', 'skewAA', 'kurAA', 'q1AA', 'medianAA', 'q3AA', 'iqrAA', 'rangeAA', 'acfAA', 'zcrAA', 'dfaAA', 'cvAA', 'tkeoAA', 'F0AA', 'P0AA', 'F0FAA', 'P0FAA', 'medianF0FAA', 'sdF0FAA', 'tlagAA', 'meanAJ', 'sdAJ', 'modeAJ', 'skewAJ', 'kurAJ', 'q1AJ', 'medianAJ', 'q3AJ', 'iqrAJ', 'rangeAJ', 'acfAJ', 'zcrAJ', 'dfaAJ', 'cvAJ', 'tkeoAJ', 'F0AJ', 'P0AJ', 'F0FAJ', 'P0FAJ', 'medianF0FAJ', 'sdF0FAJ', 'tlagAJ', 'corXY', 'corXZ', 'corYZ', 'activityDuration')

walkF <- walkF %>% filter(dataGroups == 'ms_patient') %>%
  gather(feature, value, WALK_FEATURES) 
walkF <- walkF %>% select(-c( "externalId", "createdOnTimeZone" , "userSharingScope",
                              "substudyMemberships", "error")) 

walkF_week_averaged =  walkF %>% 
  dplyr::select(healthCode, participant_week, feature, value) %>%
  dplyr::group_by(healthCode, participant_week, feature) %>% 
  dplyr::summarise_all(.funs=c(mean), na.rm=T) 
```

<br>
<br>

```{r, neuroQoLCors}
## Correlations- All Weeks
neurCog_allWeeks_walkF <- get_neuroQOL_cors(walkF_week_averaged)

## Correlations- First common week
neurCog_firstCommonWeek_walkF <- get_neuroQOL_cors(walkF_week_averaged,
                                                   use_first_common_week=T)
```


##### Correlation Walk features(All Weeks) with Neuro-QoLs

```{r,  fig.align='center', fig.width=14, fig.height=8, dpi=200}
p1 <- ggplot(neurCog_allWeeks_walkF, aes(x=cor, y=-log10(p.val.adj))) + theme_few() + geom_point(size=.7)  + facet_grid( . ~ survey )
p1 <- p1 + scale_color_manual(values=c("#d01c8b", "#4dac26")) + theme(text = element_text(size=15)) + xlab('correlation(spearman)') + geom_hline(yintercept=2, color='grey30', size=.8) + theme(panel.spacing = unit(2, "lines"))
p1
ggsave("FIGURES/walkF_n_NeuroQOLs_corr_allWeeks_volcanoPlot.jpeg", plot=p1, height=4, width=10, units="in", dpi=300)

```


##### Scatter plot top 2 walking features(All Weeks) 
```{r, fig.align='center', fig.width=8, fig.height=5, dpi=200}
#View(neurCog_allWeeks_walkF %>% arrange(desc(abs(cor))))
p1 <- get_scatter_plot(walkF_week_averaged, nQOL_lowExtremity, x='P0FY', y='TScore')
p2 <- get_scatter_plot(walkF_week_averaged, nQOL_lowExtremity, x='q1Z', y='TScore')
p3 <- grid.arrange(p1,p2, nrow=1)
p3
ggsave("FIGURES/walkF_top_2_feature_scatterPlot_allWeek.png", p3, height=3, width=9, units="in", dpi=150)
```


-----

#####  Correlations Walk features(first common week) with Neuro-QoLs

```{r  fig.align='center', fig.width=14, fig.height=8, dpi=200}
p1 <- ggplot(neurCog_firstCommonWeek_walkF, aes(x=cor, y=-log10(p.val.adj))) + theme_few() + geom_point(size=.7)  + facet_grid( . ~ survey )
p1 <- p1 + scale_color_manual(values=c("#d01c8b", "#4dac26")) + theme(text = element_text(size=15)) + xlab('correlation(spearman)') + geom_hline(yintercept=2, color='grey30', size=.8) + theme(panel.spacing = unit(2, "lines"))
p1
ggsave("FIGURES/walkF_n_NeuroQOLs_corr_firstCommonWeeks_volcanoPlot.jpeg", plot=p1, height=4, width=10, units="in", dpi=300)
```



```{r, eval=F}
### Select top features
# View(neurCog_firstCommonWeek_walkF %>% arrange(desc(abs(cor))))
# p1 <- get_scatter_plot(walkF_week_averaged, nQOL_lowExtremity, x='F0AA', y='TScore', use_first_common_week = T)
# p2 <- get_scatter_plot(walkF_week_averaged, nQOL_lowExtremity, x='tlagAA', y='TScore', use_first_common_week = T)
# p3 <- grid.arrange(p1,p2, nrow=1)
# ggsave("analysis/Analytical_Paper_2/FIGURES/walkF_top_2_feature_scatterPlot_firstCommonWeek.png", p3, height=3, width=9, units="in", dpi=150)
```


----------


##### Association between walk feature(turning time) across all weeks with baseline PDDS survey

```{r fig.align='center', fig.width=8, fig.height=5, dpi=100}
##### PDDS
tmp_baselineChar <- baselineChar %>% 
  filter(!is.na(overallPhysicalAbility)) %>%
  filter(dataGroups == 'ms_patient') %>%
  select(healthCode, overallPhysicalAbility)

walkF_averaged <- walkF %>% group_by(healthCode, feature) %>% 
  dplyr::summarise(value = mean(value, na.rm = T)) %>%
  inner_join(tmp_baselineChar) %>%
  mutate(overallPhysicalAbility = factor(overallPhysicalAbility, levels=c('normal', 'milddisability', 'moderatedisability', 'gaitdisability')))

tmp_df <- walkF_averaged  %>%
  group_by(feature) %>%
  nest() %>%
  mutate(res = purrr::map(data, function(x){
    anova(lm(value ~ overallPhysicalAbility, data=x))
  })) %>%
  mutate(glance = res %>% map(broom::tidy))
tmp_get_anova_pval <- function(x){
  x %>% filter(term == 'overallPhysicalAbility') %>% .$p.value
}
tmp_df <- tmp_df %>% mutate(p.val = unlist(glance  %>% map( tmp_get_anova_pval ))) %>%
  select(-glance, -data, -res)

p <- ggboxplot(walkF_averaged %>% filter(feature == 'P0FY'), 
               x = "overallPhysicalAbility", y = "value", 
               font.label = list(size=6, face="plain"),
               ylab='Walking P0FY', width=.5, size=.3,
               color = "#F25F5C")
my_comparisons <- list( c("normal", "moderatedisability"), c("normal", "gaitdisability"))
p <- p + stat_compare_means(comparisons = my_comparisons) + # Add pairwise comparisons p-value
  stat_compare_means(label.y = 0, label.x = 1.2, label.size = 0.25) 
p <- p + theme_few()
p
ggsave("FIGURES/Walk_feature_P0FY_physicalDisability_boxplot.png", p, height=4, width=8, units="in", dpi=300)


```



```{r, syn.store, eval=F}
# Knit html document and push to synapse
thisFilePrefix = "walk_features_analysis"
thisFileName = paste0(thisFilePrefix, '.Rmd')
html.obj = rmarkdown::render(thisFileName, output_format = 'html_document')


thisFilePrefix = "walk_features_analysis"
thisFileName = paste0(thisFilePrefix, '.Rmd')
gtToken = '~/.ssh/apratap_github_token_20190219.txt';
githubr::setGithubToken(as.character(read.table(gtToken)$V1))
thisRepo <- githubr::getRepo(repository = "Sage-Bionetworks/elevateMS_analysis", ref="branch", refName='master')
thisFile_github_permaLink <- githubr::getPermlink(repository = thisRepo, repositoryPath=paste0('analysis/Analytical_Paper_2/',thisFileName))
thisFile_synapse = File(paste0(thisFilePrefix, '.html'), parentId ='syn11315047')
###Store on Synapse
synStore(thisFile_synapse, executed=thisFile_github_permaLink)
unlink(paste0(thisFilePrefix, '.html'))
```


