---
title: "ElevateMS - on-going summary"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: default
  html_notebook: default
---

```{r global_options, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(fig.path='Figs/', echo=FALSE, warning=FALSE, message=FALSE)
```

```{r}
Sys.setenv(TZ='GMT')
library(synapseClient)
synapseLogin()
library(install.load)
install_load(c('plyr', 'tidyverse', 'data.table', 'lubridate', 'ggpubr'))
install_load('ggthemes', 'gridExtra', 'devtools')
```

```{r}
stringfy <- function(x){
  gsub('[\\[\"\\]]','',x, perl=T) 
}

DAYS_SINCE_LAUNCH = as.numeric(Sys.Date() - lubridate::ymd("2017-08-14"))
WEEKS_SINCE_LAUNCH = ( (DAYS_SINCE_LAUNCH - 1) %/% 7) + 1
```


```{r}
masterTable <- "syn9758009"  #poorly named elevate-ms-appVersion
#remove all testing users and records created before Monday, August 14, 2017 12:00:00 AM (GMT)
userActivity <- synTableQuery(paste("select * from", masterTable, "WHERE dataGroups NOT LIKE '%test%' AND createdOn > 1502668800000"))
userActivity <- userActivity@values

#Data Manipulation
userActivity <- userActivity %>% dplyr::mutate(createdOnTimeZone = as.numeric(createdOnTimeZone)/100,
                                               createdOn = lubridate::ymd_hms(createdOn, tz='UTC'),
                                               originalTable = gsub('elevate-ms-', '', originalTable))

#get start dates for people 
userStartDates <- userActivity %>% dplyr::group_by(healthCode) %>% 
  dplyr::summarise(participantStartDate = min(lubridate::date(createdOn)))
userActivity <- userActivity %>% inner_join(userStartDates)

userActivity <- userActivity %>% 
  dplyr::mutate(createdOn_localTime = createdOn + lubridate::hours(createdOnTimeZone),
                participant_day = as.numeric(lubridate::date(createdOn) - participantStartDate ) + 1,
                participant_week = ((participant_day - 1) %/% 7 ) + 1,
                study_day = as.numeric(lubridate::date(createdOn) - lubridate::ymd("2017-08-14")) + 1,
                study_week = ((study_day - 1) %/% 7 ) + 1,
                currentDate = Sys.Date()
                )
```


```{r}
STUDY_HEALTHCODES <- unique(userActivity$healthCode)
total_elevateMS_users <- n_distinct(userActivity$healthCode)
num_MS_patients <- userActivity %>% dplyr::filter(dataGroups %like% 'ms_patient') %>% .$healthCode %>% n_distinct()
num_controls <- userActivity %>% dplyr::filter(dataGroups %like% 'control') %>% .$healthCode %>% n_distinct()
MS_patients_dataContrib <- round(table(userActivity$dataGroups) / nrow(userActivity) * 100, digits=2)[2]
```


----------


#### Summary stats
* Weeks since launch(Aug 14, 2017): `r  WEEKS_SINCE_LAUNCH`
* Total users:   `r total_elevateMS_users`
* MS patients:    `r num_MS_patients`
* Controls:       `r num_controls`
* Data Contributed (MS patients): `r MS_patients_dataContrib` 


---------


#### Errors Detected

```{r}
records_with_wrong_createdOn_dates <- sum(lubridate::date(lubridate::ymd_hms(userActivity$createdOn)) > Sys.Date())
```


```{r}
#filter bad data
userActivity <- userActivity %>% dplyr::filter(lubridate::ymd_hms(createdOn)  <= Sys.Date())
```


* Records with malformed timestamp -  `r records_with_wrong_createdOn_dates`

-------

### Enrollment summary

```{r}
enrollment <- userActivity %>% select(healthCode, study_week, dataGroups) 
enrollment <- enrollment[!duplicated(enrollment),]
enrollment <- plyr::ldply(1:max(enrollment$study_week), function(x){
  untilNow <- enrollment %>% filter(study_week < x) %>% .$healthCode %>% unique()
  thisWeek <- enrollment %>% filter(study_week == x) %>% .$healthCode %>% unique()
  newUsers_thisweek <- setdiff(thisWeek, untilNow)
  res <- enrollment %>% select(healthCode, dataGroups)
  res <- res[!duplicated(res),]
  res <- res %>% filter(healthCode %in% newUsers_thisweek)
  data.frame('week'=x,
             'ms_patients' = res %>% filter(dataGroups == 'ms_patient') %>% nrow(),
             'controls' = res %>% filter(dataGroups == 'control') %>% nrow()) %>%
    gather(type, num, 2:3)
})

enrollment <- enrollment %>% mutate(type = factor(type))
p1 <- ggplot(data=enrollment, aes(x=week, y=num, fill=type )) + geom_bar(stat="identity", position="dodge", width = .7) + theme_bw() + scale_x_discrete(limits=seq(1,max(enrollment$week),2))  + ylab('#people enrolled') + xlab('week since launch')
p1 <- p1 + theme_few() + scale_fill_manual(values=c("#A5BE00", "#FC4E07"),  labels=c('Control', 'MS patient')) + theme(legend.position = c(0.85, 0.9))
p1 <- p1 + theme(text = element_text(size=15)) + ggtitle('#Users joining per week')
p1 <- p1 + geom_vline(xintercept=WEEKS_SINCE_LAUNCH, colour="grey40", size=1, linetype=3)
```



```{r}
### This is mainly to figure out the #users that have been in study for atleast #weeks irrespective of the data contributed
user_time_in_study <- userActivity %>% dplyr::group_by(healthCode, dataGroups) %>%
  dplyr::summarise(participantStartDate = min(lubridate::date(createdOn))) %>%
  dplyr::mutate(currentDate = Sys.Date(),
                days_in_study =  as.numeric(currentDate - participantStartDate) + 1,
                weeks_in_study =  ((days_in_study - 1 ) %/% 7 ) + 1)

userWeeks <- user_time_in_study %>% dplyr::group_by(dataGroups, weeks_in_study) %>%
  dplyr::summarise(numUsers = n_distinct(healthCode))
userWeeks <- userWeeks %>% ddply(.variables=c('dataGroups', 'weeks_in_study'),
                    .fun = function(x){
                      tmp <- userWeeks %>% dplyr::filter(weeks_in_study >=  unique(x$weeks_in_study) & dataGroups == unique(x$dataGroups))
                      data.frame('totalUsersReachedThisWeek' = sum(tmp$numUsers))
                    })

#People active each week since study start
userActiveEachWeek <- userActivity %>% dplyr::group_by(dataGroups, study_week) %>%
  dplyr::summarise(uniqUsers = n_distinct(healthCode))

p2 <- ggplot(data=userActiveEachWeek, aes(x=study_week, y=uniqUsers, fill=dataGroups )) + geom_bar(stat="identity", width = .5) + theme_bw() + scale_x_discrete(limits=seq(1,max(userActiveEachWeek$study_week),2))
p2 <- p2 +  labs(col="User type\n") + scale_fill_manual(values=c("#A5BE00", "#FC4E07"), labels=c('Control', 'MS patient')) 
p2 <- p2 + theme_few() + theme(legend.position = c(0.85, 0.9))
p2 <- p2 + theme(text = element_text(size=15)) + ggtitle('#Users active each week') + ylab('#people') + xlab('week since launch')
p2 <- p2 + geom_vline(xintercept=WEEKS_SINCE_LAUNCH, colour="grey40", size=1, linetype=3)
```

```{r,fig.width=15, fig.height=6}
grid.arrange(p1,p2, ncol=2)
```

-------------

### Compliance

```{r, fig.width=7, fig.height=5, fig.align='center'}
#Since the study is still going on we are not dividing by the all users rather number of unique users in each week of the study
overallCompliance <- userActivity %>% dplyr::group_by(dataGroups, participant_week) %>%
  dplyr::summarise(uniqUsers = n_distinct(healthCode))

overallCompliance <- merge(overallCompliance, userWeeks, by.x=c('dataGroups', 'participant_week'),
      by.y = c("dataGroups", "weeks_in_study"))
overallCompliance <- overallCompliance %>% dplyr::mutate(percent = round( (uniqUsers /totalUsersReachedThisWeek)*100, digits=2))

p3 <- ggplot(data=overallCompliance, aes(x=participant_week, y=percent )) + geom_bar(stat="identity", position="dodge", width = .4) + theme_bw() + scale_x_discrete(limits=seq(1,max(overallCompliance$participant_week),2)) + ggtitle('percent active users per week')
p3 <- p3 + theme_few() + scale_fill_manual(values=c('#00AFBB')) +  theme(text = element_text(size=15))
p3 <- p3 + xlab('#weeks enrolled') +  theme(text = element_text(size=15))
```


```{r}
pro_surveys <- userActivity %>% filter( ( originalTable %like% 'NeuroQOL' | originalTable %like% 'MSIS') & dataGroups == 'ms_patient')
pro_surveys_compliance <- pro_surveys %>% group_by(dataGroups, participant_week, originalTable) %>% 
  dplyr::summarise(num = n_distinct(healthCode))
pro_surveys_compliance <- merge(pro_surveys_compliance, userWeeks, by.x=c('dataGroups', 'participant_week'), by.y=c('dataGroups', 'weeks_in_study'))
pro_surveys_compliance <- pro_surveys_compliance %>% dplyr::mutate(percent = round((num/totalUsersReachedThisWeek) * 100, digits=2))
pro_surveys_compliance['Survey'] = pro_surveys_compliance$originalTable
pro_surveys_compliance$originalTable <- NULL
pro_surveys_compliance['Survey'] = gsub('NeuroQOL-', '',pro_surveys_compliance$`Survey`)
p4 <- ggplot(data=pro_surveys_compliance, aes(x=participant_week, y=percent, color=Survey ))  + geom_point() + geom_line(size=1.5)
p4 <- p4 + theme_few() +  scale_color_manual(values=c( "#2EC4B6", "#E71D36", "#FF9F1C", '#95C623')) 
p4 <- p4 +  ggtitle('% Surveys Completed')  + xlab('#weeks enrolled') +  theme(text = element_text(size=15))
```

```{r}
activeSensor_tasks <- userActivity %>% 
  filter( (originalTable %like% 'Tremor' | originalTable %like% 'Tapping' | originalTable %like%  'Walking' | originalTable %like% 'Brain') & dataGroups == 'ms_patient' )
activeSensor_tasks_compliance <- activeSensor_tasks %>% group_by(dataGroups, participant_week, originalTable) %>% 
  dplyr::summarise(num = n_distinct(healthCode))
activeSensor_tasks_compliance <- merge(activeSensor_tasks_compliance, userWeeks, by.x=c('dataGroups', 'participant_week'), by.y=c('dataGroups', 'weeks_in_study'))
activeSensor_tasks_compliance <- activeSensor_tasks_compliance %>% dplyr::mutate(percent = round((num/totalUsersReachedThisWeek) * 100, digits=2))
activeSensor_tasks_compliance['sensorActivity'] = activeSensor_tasks_compliance$originalTable
activeSensor_tasks_compliance$originalTable <- NULL
activeSensor_tasks_compliance['sensorActivity'] = gsub(' Activity.*', '',activeSensor_tasks_compliance$`sensorActivity`, perl=T)
activeSensor_tasks_compliance['sensorActivity'] = gsub('-.*', '',activeSensor_tasks_compliance$`sensorActivity`, perl=T)

p5 <- ggplot(data=activeSensor_tasks_compliance, aes(x=participant_week, y=percent, color=sensorActivity ))  + geom_point() + geom_line(size=1.5)
p5 <- p5 + theme_few() +  scale_color_manual(values=c( "#2EC4B6", "#E71D36", "#FF9F1C", "#011627")) 
p5 <- p5 +  ggtitle('% Active(non-survey) tasks completed')  + xlab('#weeks enrolled') +  theme(text = element_text(size=15))
```




```{r}
otherShortSurveys <-  userActivity %>% 
  filter( (originalTable %like% 'Daily Check' | originalTable %like%  'Symptoms Survey' | originalTable %like% 'Triggers Survey' |  originalTable %like%  'Factors Survey') & dataGroups == 'ms_patient' )
otherShortSurveys_compliance <- otherShortSurveys %>% group_by(dataGroups, participant_week, originalTable) %>% 
  dplyr::summarise(num = n_distinct(healthCode))
otherShortSurveys_compliance <- merge(otherShortSurveys_compliance, userWeeks, by.x=c('dataGroups', 'participant_week'), by.y=c('dataGroups', 'weeks_in_study'))
otherShortSurveys_compliance <- otherShortSurveys_compliance %>% dplyr::mutate(percent = round((num/totalUsersReachedThisWeek) * 100, digits=2))
otherShortSurveys_compliance['otherSurveys'] = otherShortSurveys_compliance$originalTable
otherShortSurveys_compliance$originalTable <- NULL
otherShortSurveys_compliance['otherSurveys'] = gsub('-v1', '',otherShortSurveys_compliance$`otherSurveys`, perl=T)

p6 <- ggplot(data=otherShortSurveys_compliance, aes(x=participant_week, y=percent, color=otherSurveys ))  + geom_point() + geom_line(size=1.5)
p6 <- p6 + theme_few() +  scale_color_manual(values=c( "#2EC4B6", "#E71D36", "#FF9F1C", '#011627')) 
p6 <- p6 +  ggtitle('% Other short surveys tasks completed')  + xlab('#weeks enrolled') +  theme(text = element_text(size=15))
```


```{r,fig.width=15, fig.height=10}
grid.arrange(p3,p4,p5,p6, ncol=2)
```

-------------


### Demographics Summary

```{r}
demog <-  synTableQuery(paste("select * from syn10295288"))@values
demog$metadata.json.dataGroups <- NULL
colnames(demog) <- gsub('.json.answer', '',colnames(demog))
colnames(demog)  <- gsub('metadata.json.', '',colnames(demog))
demog <- demog %>% dplyr::select(-scheduledActivityGuid, -endDate, -endDate.timezone, -appVersion, -phoneInfo, -validationErrors, -startDate.timezone, -createdOn, -createdOnTimeZone, -recordId, -uploadDate, -externalId) %>%
  filter(dataGroups %in% c('control', 'ms_patient') & healthCode %in% STUDY_HEALTHCODES) %>%
  dplyr::mutate(startDate = as.Date(lubridate::ymd_hms(startDate)))

demog <- ddply(.data = demog, .variables = c('healthCode'), .fun = function(x){
  x <- x %>% arrange(desc(startDate))
  x[1,]
})
race <- demog %>% tidyr::gather(race, value, 7:16) %>% dplyr::filter(value == 'TRUE') %>% 
  dplyr::mutate(race = gsub('race.','',race)) %>% select(healthCode, race) %>% group_by(healthCode) %>%
  dplyr::summarise(race = paste(race,collapse=','))
demog <- merge(demog, race) %>% select(-c(7:16))


profiles <- synTableQuery(paste("select * from syn10235463"))@values
profiles <- profiles %>% dplyr::filter(healthCode %in% STUDY_HEALTHCODES) %>%
  dplyr::transmute(healthCode = healthCode, 
                   startDate = as.Date(lubridate::ymd_hms(createdOn)),
                   zipcode = demographics.zipcode, age = demographics.age,
                   gender = demographics.gender, height = demographics.height,
                   weight = demographics.weight, education = demographics.education,
                   health_insurance = demographics.health_insurance,
                   employment = demographics.employment, race = demographics.race,
                   userSharingScope=NA) %>%
  dplyr::group_by(healthCode) %>%
  dplyr::summarise( startDate = unique(startDate)[1], zipcode = unique(zipcode)[1],
                    age = unique(age)[1], gender = unique(gender)[1], height = unique(height)[1],
                    weight = unique(weight)[1], education = unique(education)[1],
                    health_insurance = unique(health_insurance)[1], employment=unique(employment)[1],
                    race = unique(race)[1], userSharingScope=unique(userSharingScope)[1]) %>%
  dplyr::mutate(race = stringfy(race))

#Add age to demog
demog <- merge(demog, profiles %>% dplyr::select(healthCode, age), all.x=T)

demog_derived_from_profiles <- profiles %>% dplyr::filter(!healthCode %in% demog$healthCode)
dataGroups <- userActivity %>% select(healthCode, dataGroups)
dataGroups <- dataGroups[!duplicated(dataGroups),]
demog_derived_from_profiles <- merge(demog_derived_from_profiles , dataGroups, all.x=T)


demog_derived_from_profiles <- demog_derived_from_profiles %>% 
  dplyr::select(healthCode, age, dataGroups, userSharingScope, gender, height,
                weight, zipcode, education, health_insurance, employment, startDate, race)


tmp_df <- data.frame(dataGroups = c('control', 'ms_patient'),
                     num = c(num_controls, num_MS_patients), stringsAsFactors = F)

percent_demog_data_compliance =  round( (n_distinct(demog$healthCode)/total_elevateMS_users) *100, digits=2)

percent_demog_data_from_profiles_compliance =  round( (n_distinct(demog_derived_from_profiles$healthCode)/total_elevateMS_users) *100, digits=2)

demog_total <- rbind(demog, demog_derived_from_profiles)
```



* Demographics data available for : `r  n_distinct(demog$healthCode)` individuals | `r percent_demog_data_compliance` %

* Demographics data obtained from profiles : `r  n_distinct(demog_derived_from_profiles$healthCode)` individuals | `r percent_demog_data_from_profiles_compliance` %

#### Missingness in demographic data

```{r, align='center', fig.width=5, fig.height=5}
missingData <- apply(demog_total,2, function(x){
  round( (sum(is.na(x) | x == "") / nrow(demog_total)) *100, digits=2)
})
tmp_df <- data.frame(col = names(missingData), percentMissing = as.numeric(missingData)) %>% arrange(percentMissing)

ggplot(data=tmp_df, aes(x=col, y=percentMissing)) + geom_bar(stat="identity") + theme_few() + coord_flip() + scale_y_continuous(limits=c(0,100)) + xlab('demographic var')
```

--------


```{r}
days_userActive <- userActivity %>% group_by(healthCode) %>% dplyr::summarise(numDaysActive = n_distinct(participant_day))

demog_total['demogData'] = FALSE
demog_total$demogData[!is.na(demog_total$zipcode)] = TRUE

tmp <- merge(days_userActive, demog_total %>% select(healthCode, demogData))
ggplot(data=tmp, aes(x=demogData, y=numDaysActive)) + geom_boxplot() + theme_few() + xlab('Participants who gave demographics data')

```


--------


```{r}
tmp_df <- data.frame(dataGroups = c('control', 'ms_patient'),
                     num = c(num_controls, num_MS_patients), stringsAsFactors = F)

gender = demog_total %>% filter(gender %in% c('Female', 'Male')) %>% inner_join(tmp_df) %>% dplyr::group_by(dataGroups, gender, num) %>% dplyr::summarise(prop =n_distinct(healthCode)) %>% mutate(prop = round((prop / num)*100, digits=2))
p2 <- ggplot(data=gender, aes(x=gender, y=prop, fill=dataGroups )) + geom_bar(stat="identity", position="dodge", width = .7) + theme_bw()  + ylab('percent')
p2 <- p2 + theme_few() + scale_fill_manual(values=c("#A5BE00", "#FC4E07"),  labels=c('Control', 'MS patient')) + theme(legend.position = c(0.85, 0.8))
p2 <- p2 + theme(text = element_text(size=15)) + ggtitle('Gender')
```


```{r}
employment = demog_total %>% filter(!is.na(employment)) %>% inner_join(tmp_df) %>% dplyr::group_by(dataGroups, employment, num) %>% dplyr::summarise(prop =n_distinct(healthCode)) %>% mutate(prop = round((prop / num)*100, digits=2))
p1 <- ggplot(data=employment, aes(x=employment, y=prop, fill=dataGroups )) + geom_bar(stat="identity", width = .7) + theme_bw()  + ylab('percent')
p1 <- p1 + theme_few() + scale_fill_manual(values=c("#A5BE00", "#FC4E07"),  labels=c('Control', 'MS patient')) + theme(legend.position = c(0.85, 0.8))
p1 <- p1 + theme(text = element_text(size=15)) + ggtitle('Employment type') + coord_flip()
```


```{r}
p3 <- ggplot(data=demog_total %>% filter(!is.na(gender)), aes(x=gender, y=age, fill=dataGroups )) + geom_boxplot(width = .7) + theme_bw()  + ylab('Age')
p3 <- p3 + theme_few() + scale_fill_manual(values=c("#A5BE00", "#FC4E07"),  labels=c('Control', 'MS patient')) + theme(legend.position = 'none')
p3 <- p3 + theme(text = element_text(size=15)) + ggtitle('Age distribution') 
```



```{r}
health_insurance = demog_total %>% filter(!is.na(health_insurance)) %>% inner_join(tmp_df) %>% dplyr::group_by(dataGroups, health_insurance, num) %>% dplyr::summarise(prop =n_distinct(healthCode)) %>% mutate(prop = round((prop / num)*100, digits=2))
levels <- health_insurance %>% filter(dataGroups == 'ms_patient') %>% arrange(desc(prop)) %>% .$health_insurance
health_insurance$health_insurance <- factor(health_insurance$health_insurance, levels=rev(levels))
p4 <- ggplot(data=health_insurance, aes(x=health_insurance, y=prop, fill=dataGroups )) + geom_bar(stat="identity", width = .7) + theme_bw()  + ylab('percent')
p4 <- p4 + theme_few() + scale_fill_manual(values=c("#A5BE00", "#FC4E07"),  labels=c('Control', 'MS patient')) + theme(legend.position = c(0.85, 0.8))
p4 <- p4 + theme(text = element_text(size=15)) + ggtitle('Health Insurance') + coord_flip() + xlab('')
```


```{r}
race = demog_total %>% filter(!is.na(race)) %>% inner_join(tmp_df) %>% dplyr::group_by(dataGroups, race, num) %>% dplyr::summarise(prop =n_distinct(healthCode)) %>% mutate(prop = round((prop / num)*100, digits=2))
levels <- race %>% filter(dataGroups == 'ms_patient') %>% arrange(desc(prop)) %>% .$race
race$race <- factor(race$race, levels=rev(levels))
p5 <- ggplot(data=race, aes(x=race, y=prop, fill=dataGroups )) + geom_bar(stat="identity", width = .7) + theme_bw()  + ylab('percent')
p5 <- p5 + theme_few() + scale_fill_manual(values=c("#A5BE00", "#FC4E07"),  labels=c('Control', 'MS patient')) + theme(legend.position = 'none')
p5 <- p5 + theme(text = element_text(size=15)) + ggtitle('Race') + coord_flip() + xlab('')
```


```{r,fig.width=15, fig.height=15}
grid.arrange(p1,p2,p3,p4,p5, ncol=2)
```

--------

### Participant City
```{r, fig.width=15, fig.height=9}
install_load('zipcode', 'maps', 'viridis', 'leaflet' )

data(zipcode)
zipcode['zipcode_firstThree'] = substr(zipcode$zip, 1,3)
zipcode <- zipcode %>% dplyr::group_by(zipcode_firstThree) %>% 
  dplyr::summarise(longitude = median(longitude), latitude = median(latitude))

demog_total['zipcode_firstThree'] = substr(demog_total$zipcode, 1,3)
tmp_user_region <- merge(demog_total, zipcode)


#load us map data
all_states <- map_data("state")
#plot all states with ggplot
p <- ggplot()
p <- p + geom_polygon( data=all_states, aes(x=long, y=lat, group = group),colour="white", fill="grey90" ) 
p <- p + geom_jitter( data=tmp_user_region, aes(x=longitude, y=latitude, color=dataGroups), size=1.6) + theme_few()
p + scale_color_manual(values=c("#A5BE00", "#FC4E07"),  labels=c('Control', 'MS patient')) + 
  theme(legend.position = c(0.85, 0.8), legend.text = element_text(size=15), legend.title = element_text(size=0),
        axis.line=element_blank(), axis.text.x=element_blank(),
          axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),
          panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),plot.background=element_blank())
```
